# Generated by Django 4.2.7 on 2024-01-09 18:01

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'о нас',
                'verbose_name_plural': 'о нас',
            },
        ),
    ]
