# docker-compose -f docker-compose-postgres.yml up -d
# docker-compose -f docker-compose-postgres.yml down -v
# docker exec -it scraping_postgres psql --username=scraping --dbname=scraping
# данные контейнеров храняться в папке /tmp в корне проекта

version: "3.8"

services:

  postgres:
    image: postgres:14-alpine
    container_name: scraping_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: scraping
      POSTGRES_USER: scraping
      POSTGRES_DB: scraping
    volumes:
      - ../tmp/postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: scraping_pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: scraping@mail.com
      PGADMIN_DEFAULT_PASSWORD: scraping
    volumes:
      - ../tmp/pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data:
