# start: docker-compose -f docker-compose-redis.yml up -d
# stop: docker-compose -f docker-compose-redis.yml down -v
# docker ps -a
# docker images -a

version: '3.8'

services:

  redis:
    image: redis:latest
    container_name: scraping_redis
    command: redis-server
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    networks:
      - redis-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: scraping_redis-commander
    environment:
      - REDIS_HOSTS=localhost:redis:6379
      # - HTTP_USER=admin
      # - HTTP_PASSWORD=admin1234
    ports:
      - 8081:8081
    networks:
      - redis-network
    depends_on:
      - redis

volumes:
  redis:
  redis-config:

networks:
  redis-network:
    driver: bridge
