# Generated by Django 4.2.7 on 2024-01-23 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано')], default='published', max_length=50, verbose_name='Статус')),
                ('name', models.CharField(max_length=250, verbose_name='Название компании')),
                ('slug', models.SlugField(blank=True, max_length=250, verbose_name='URL-имя')),
                ('about', models.TextField(blank=True, verbose_name='О компании')),
                ('industry', models.CharField(blank=True, max_length=250, verbose_name='Отрасль')),
                ('employees', models.CharField(blank=True, max_length=250, verbose_name='Количество сотрудников')),
                ('verified', models.CharField(blank=True, max_length=250, verbose_name='Компания проверена')),
                ('website', models.CharField(blank=True, max_length=250, verbose_name='Сайт компании')),
                ('phone', models.CharField(blank=True, max_length=250, verbose_name='Телефон компании')),
                ('email', models.CharField(blank=True, max_length=250, verbose_name='E-mail компании')),
                ('company_id', models.CharField(blank=True, max_length=250, verbose_name='ID компании')),
                ('about_short', models.TextField(blank=True, verbose_name='О компании (сокращённо)')),
                ('skills', models.CharField(blank=True, max_length=1000, verbose_name='Навыки')),
                ('company_ratings', models.CharField(blank=True, max_length=250, verbose_name='Рейтинги и оценки')),
                ('rating', models.CharField(blank=True, max_length=100, verbose_name='Средний рейтинг компании')),
                ('statistics', models.CharField(blank=True, max_length=1000, verbose_name='Статистика')),
                ('addresses', models.TextField(blank=True, verbose_name='Адреса компании')),
                ('contacts', models.TextField(blank=True, verbose_name='Контакты')),
                ('links', models.TextField(blank=True, verbose_name='Ссылки')),
                ('members', models.JSONField(blank=True, null=True, verbose_name='Персонал компании')),
                ('photo', models.JSONField(blank=True, null=True, verbose_name='Фото компании')),
                ('video', models.JSONField(blank=True, null=True, verbose_name='Видео компании')),
            ],
            options={
                'verbose_name': 'компанию',
                'verbose_name_plural': 'компании',
            },
        ),
        migrations.CreateModel(
            name='ScrapingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('skill', models.CharField(max_length=100, verbose_name='Навык')),
                ('link', models.URLField(help_text='Пример: https://career.habr.com/vacancies?q=python&sort=date&type=all', max_length=1000, verbose_name='Ссылка для скрапинга')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'ссылку для скрапинга',
                'verbose_name_plural': 'ссылки для скрапинга',
            },
        ),
        migrations.CreateModel(
            name='VacancySite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('name', models.CharField(blank=True, max_length=250, verbose_name='Название сайта')),
                ('link', models.URLField(max_length=1000, verbose_name='Ссылка на сайт')),
                ('country', models.CharField(blank=True, choices=[('RUS', 'Россия'), ('UKR', 'Украина'), ('BLR', 'Белоруссия'), ('KAZ', 'Казахстан'), ('UZB', 'Узбекистан'), ('USA', 'США'), ('EU', 'Европейский Союз'), ('GBR', 'Великобритания'), ('DEU', 'Германия'), ('POL', 'Польша')], default='RUS', max_length=3, verbose_name='Страна')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'сайт вакансий',
                'verbose_name_plural': 'сайты вакансий',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано')], default='published', max_length=50, verbose_name='Статус')),
                ('title', models.CharField(max_length=250, verbose_name='Название вакансии')),
                ('slug', models.SlugField(blank=True, max_length=250, verbose_name='URL-имя')),
                ('body', models.TextField(verbose_name='Текст вакансии')),
                ('salary', models.CharField(blank=True, max_length=250, verbose_name='Зарплата')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='Адрес работы')),
                ('place', models.CharField(blank=True, max_length=250, verbose_name='Место работы')),
                ('requirements', models.CharField(blank=True, max_length=250, verbose_name='Условия и требования')),
                ('language', models.CharField(blank=True, max_length=250, verbose_name='Знание языков')),
                ('contact_name', models.CharField(blank=True, max_length=250, verbose_name='Контактное имя')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='Контактный телефон')),
                ('contact_email', models.CharField(blank=True, max_length=100, verbose_name='Контактный e-mail')),
                ('vacancy_id', models.CharField(max_length=250, verbose_name='ID вакансии')),
                ('text_date', models.CharField(blank=True, max_length=250, verbose_name='День создания (текст с сайта вакансий)')),
                ('datetime', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время создания на сайте вакансий')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacancy.company', verbose_name='Компания')),
                ('scraping_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacancy.scrapinglink', verbose_name='Ссылка для скрапинга')),
                ('scraping_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacancy.vacancysite', verbose_name='Вакансия с сайта')),
            ],
            options={
                'verbose_name': 'вакансию',
                'verbose_name_plural': 'вакансии',
                'ordering': ['-datetime'],
            },
        ),
        migrations.AddField(
            model_name='scrapinglink',
            name='scraping_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancy.vacancysite', verbose_name='Скрапинг на сайте'),
        ),
        migrations.AddField(
            model_name='company',
            name='scraping_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacancy.vacancysite', verbose_name='Компания с сайта'),
        ),
    ]
